# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-intel" "coretemp" "nct6775" ];
  boot.extraModulePackages = [ ];

  hardware.opengl.extraPackages = with pkgs; [
    rocm-opencl-icd
    rocm-opencl-runtime
  ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/259e52bc-6c98-451e-8e29-9634663bfc03";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/6B87-6A80";
      fsType = "vfat";
    };

  fileSystems."/mnt/biggerdata" = 
    {
      device = "/dev/disk/by-uuid/5f92d69e-2264-43b7-a2f1-fe7703cd350d";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/8a48019b-72fd-44ec-b8c5-6db3e775141f"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
