[tasks.default]
    links = [
        [".config/nvim"],
        [".xmonad"],
        [".xmobarrc"],
        [".gitconfig"],
        [".gitignore_global"],
        [".config/fish"],
        [".config/sway"],
        [".config/swaylock"],
        [".config/waybar"],
    ]
